-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 15:05:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nuovoProgettoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nuovoProgettoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nuovoProgettoo` DEFAULT CHARACTER SET utf8 ;
USE `nuovoProgettoo` ;

-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`Utenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`Utenti` (
  `idUtenti` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Cognome` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `DataDiNascita` DATE NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtenti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`Magazzino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`Magazzino` (
  `idMagazzino` INT NOT NULL AUTO_INCREMENT,
  `Capacità` INT NULL,
  `Sede` VARCHAR(45) NULL,
  PRIMARY KEY (`idMagazzino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`Reparti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`Reparti` (
  `idReparto` INT NOT NULL AUTO_INCREMENT,
  `NomeReparto` VARCHAR(45) NULL,
  PRIMARY KEY (`idReparto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`ProdottiInVendita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`ProdottiInVendita` (
  `idProdotto` INT NOT NULL AUTO_INCREMENT,
  `NomeProdotto` VARCHAR(45) NULL,
  `Prezzo` FLOAT NULL,
  `Id_magazzino` INT NULL,
  `CasaProduttrice` INT NULL,
  `Reparti_idReparto` INT NOT NULL,
  `Magazzino_idMagazzino` INT NOT NULL,
  `Quantità` INT NULL,
  PRIMARY KEY (`idProdotto`),
  INDEX `fk_ProdottiInVendita_Reparti1_idx` (`Reparti_idReparto` ASC),
  INDEX `fk_ProdottiInVendita_Magazzino1_idx` (`Magazzino_idMagazzino` ASC),
  CONSTRAINT `fk_ProdottiInVendita_Reparti1`
    FOREIGN KEY (`Reparti_idReparto`)
    REFERENCES `nuovoProgettoo`.`Reparti` (`idReparto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProdottiInVendita_Magazzino1`
    FOREIGN KEY (`Magazzino_idMagazzino`)
    REFERENCES `nuovoProgettoo`.`Magazzino` (`idMagazzino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`Recensioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`Recensioni` (
  `Utenti_idUtenti` INT NOT NULL,
  `ProdottiInVendita_idProdotto` INT NOT NULL,
  `Data` DATE NULL,
  `Valutazione` INT NULL,
  `Commento` VARCHAR(1000) NULL,
  PRIMARY KEY (`Utenti_idUtenti`, `ProdottiInVendita_idProdotto`),
  INDEX `fk_Recensiscono_ProdottiInVendita1_idx` (`ProdottiInVendita_idProdotto` ASC),
  CONSTRAINT `fk_Recensiscono_Utenti`
    FOREIGN KEY (`Utenti_idUtenti`)
    REFERENCES `nuovoProgettoo`.`Utenti` (`idUtenti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recensiscono_ProdottiInVendita1`
    FOREIGN KEY (`ProdottiInVendita_idProdotto`)
    REFERENCES `nuovoProgettoo`.`ProdottiInVendita` (`idProdotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`Appartengono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`Appartengono` (
  `Reparti_idReparto` INT NOT NULL,
  `ProdottiInVendita_idProdotto` INT NOT NULL,
  PRIMARY KEY (`Reparti_idReparto`, `ProdottiInVendita_idProdotto`),
  INDEX `fk_Appartengono_ProdottiInVendita1_idx` (`ProdottiInVendita_idProdotto` ASC),
  CONSTRAINT `fk_Appartengono_Reparti1`
    FOREIGN KEY (`Reparti_idReparto`)
    REFERENCES `nuovoProgettoo`.`Reparti` (`idReparto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appartengono_ProdottiInVendita1`
    FOREIGN KEY (`ProdottiInVendita_idProdotto`)
    REFERENCES `nuovoProgettoo`.`ProdottiInVendita` (`idProdotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuovoProgettoo`.`Acquisti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuovoProgettoo`.`Acquisti` (
  `Utenti_idUtenti` INT NOT NULL,
  `ProdottiInVendita_idProdotto` INT NOT NULL,
  `Quantità` INT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`Utenti_idUtenti`, `ProdottiInVendita_idProdotto`),
  INDEX `fk_Acquistano_ProdottiInVendita1_idx` (`ProdottiInVendita_idProdotto` ASC),
  CONSTRAINT `fk_Acquistano_Utenti1`
    FOREIGN KEY (`Utenti_idUtenti`)
    REFERENCES `nuovoProgettoo`.`Utenti` (`idUtenti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acquistano_ProdottiInVendita1`
    FOREIGN KEY (`ProdottiInVendita_idProdotto`)
    REFERENCES `nuovoProgettoo`.`ProdottiInVendita` (`idProdotto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
